name: bicycle_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

fonts:
  - family: CookieRun
    fonts:
    - assets: assets/font/CookieRun_Regular.ttf

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  geolocator: ^8.1.1
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  location: ^4.3.0
  geoflutterfire: ^3.0.2
  rxdart: ^0.27.3
  cloud_firestore: ^3.1.7
  http: ^0.13.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/